### ISSUE TITLE
St2 installer should direct users to Self-signed CA

### ISSUE THREAD

**Issue by jfryman** [StackStorm/st2installer#29]
If the user does a self-signed certificate, then we need to direct the user to a new endpoint in a new target window. The new endpoint: https://ip/ssl.

New page looks like this. Not glamorous, but gets the job done.

<img width="684" alt="stackstorm_self-signed_ca_and_slack" src="https://cloud.githubusercontent.com/assets/20028/9867547/d604d576-5b23-11e5-9f90-e880bd3f59d4.png">

Post puppet run, this endpoint and certificate are available. A modal popup at the end with links? Or even, just a hotlink to the certificate itself (./ssl/st2_root_ca.cer). The page exists for a link to the CACert wiki. Ideas on best ways most appreciated. 

Goals are:
* Get the user the root CA
* get them to install it, and answer questions if they have them.

**Comment by emedvedev** [comment]
We can integrate it into installer final page instead of having more pages. Here's what I could come up with:

![screenshot 2015-09-15 19 40 12](https://cloud.githubusercontent.com/assets/145218/9877992/b1ae96e2-5bd9-11e5-9607-3b466ee0f452.png)

We check if the CA is present with an HTTP request and show a notice to download it if it is. @jfryman will that do?

Notice: we really need to test it before rolling into production, because my st2express doesn't have this root CA generation, apparently (I've updated). Is it how it's supposed to be?

**Comment by st2stanley** [comment]
I like this a lot better than a separate page. I’m just going to rip mine out.

As far as you not generating the certs, it should have landed with https://github.com/StackStorm/st2workroom/pull/106 <https://github.com/StackStorm/st2workroom/pull/106>. Note that the `rsync` on vagrant does not automatically push up new code into the host. Try running `vagrant rsync` and then `vagrant provision` again to see if the CA will get generated.
